#!/bin/bash
#PBS -l nodes=1:ppn=3

## Variables to pass 
#prot : prot name
#mark : mark
#tree : tree file
#prefix : prefix for output

mark=$(echo "$mark" | sed -e 's/bbb/,,/g')

aln=${prot}.fa

echo "Job started on $HOSTNAME at time : $(date)"

cmd="ete3 evol --noimg -t $tree --alg $aln -o ${prefix}_branch-site --mark $mark --models bsA bsA1 M1 --tests bsA,M1 bsA,bsA1 --cpu 3"

echo $cmd
$cmd > ${prefix}_branch-site.out

echo "Job finished on $HOSTNAME at time : $(date)"

