#!/usr/bin/python
import argparse
#add gitRepository
gitRepository='SEDMATCHGITREPO'
version='SEDMATCHGITVERSION'
year=2016
author='Julien Fouret'
contact='julien@fouret.me'
##parse argument
parser = argparse.ArgumentParser(description='Make reports for phylo',epilog="Version : "+str(version)+"\n"+str(year)+"\nAuthor : "+author+" for more informations or enquiries please contact "+contact,formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument('-aln_dir', metavar='/path', required=True, help="alignement repositories")
parser.add_argument('-outDir', metavar='/path', required=True, help="path of the output directory from positive selection analysis")
parser.add_argument('-filter', metavar='name', required=True, help="Name of the filter used in gwAlign")
parser.add_argument('-general_rmd', metavar='/path',default=gitRepository+'/template/report.rmd', required=False, help="path of general rmd file")
parser.add_argument('-general_biblio', metavar='/path',default=gitRepository+'/template/positiveSelection.bibtex', required=False, help="path of general bibliography file")
parser.add_argument('-gene_rmd', metavar='/path',default=gitRepository+'/summary.rmd', required=False, help="path of gene rmd file")
parser.add_argument('-adj', metavar='/path', default='yes',required=False, help="yes if adjusment, anything else for no adjustment")
parser.add_argument('-genePythia', metavar='/path', default='SEDMATCHGENEPYTHIA',required=False, help="script for bibliography")

args=parser.parse_args()
### import
from Bio.Seq import Seq
from Bio.Alphabet import generic_dna, generic_protein
import os
import sys
import glob
import subprocess
import copy
import re
from jupype import *

#variable in args
rootedDir=loadRoot(args.outDir)
alnRepo=os.path.abspath(args.aln_dir)

def tcod(strNucl):
	# from nucl position to codon position
	return str(((int(strNucl)+2)/3))

###Put in a separate function
def getOpt(fileName,module,option):
	head = None
	with open(fileName,'r') as file:
		for line in file.readlines():
			if head is None:
				head=dict()
				index=0
				for var in line.rstrip().split(';'):
					head[var]=index
					index+=1
				continue
			lineList=line.rstrip().split(';')
			if lineList[head['module']]==module and lineList[head['option']]==option:
				return(lineList[head['value']])
				break
###

def Report(rmdFile,gene,biblio='None',jobID=None):
	global rootedDir
	workdir=rootedDir.reports+'/'+gene
	cmdList=list()
	cmdList.append('cp '+rmdFile+' .')
	if biblio!='None':
		cmdList.append('cp '+biblio+' .')
	cmdList.append('rmd=$(ls *rmd);Rscript -e "rmarkdown::render(\'${rmd}\')"')
	cmdList.append('rm *.rmd')
	submitQsubWithPBS(createPBS(cmdList,gene+'_rep',rootedDir.pbsLogs+'/'+gene+'_rep.e',rootedDir.pbsLogs+'/'+gene+'_rep.o',workdir=workdir,waitList=jobID))

def readBEB(geneName):
	global rootedDir
	fileName=glob.glob(rootedDir.paml+'/'+geneName+'/*/bsA.*/out')[0]
	file=open(fileName,'r')
	BEB=""
	level=0
	for line in file.readlines():
		line=line.rstrip()
		if level==3:
			break
		if level==2:
			if line=='':
				level=3
			else:
				BEB=BEB+"\t".join(line.lstrip().split(' '))+"\n"
		if level==1:
			level=2
		if line=='Bayes Empirical Bayes (BEB) analysis (Yang, Wong & Nielsen 2005. Mol. Biol. Evol. 22:1107-1118)':
			level=1
	file.close()
	with open('BEB.tab','w') as file:
		file.write(BEB)

genepythiaGit=Git(args.genePythia)
genepythia=gitCommand(genepythiaGit,'genePythia.py')
genepythia.log()
reGeneName=re.compile('^(dup[0-9]+_)*([kg_]*[rs_]*[sp_]*)(.*)$')

#consNameDict=
consNameDict=dict()
with open(args.aln_dir+'/reports/consNameDict.tab','r') as consNameDictFile:
	for line in consNameDictFile.readlines():
		key,value=line.rstrip().split("\t")
		consNameDict[key]=value

def byGeneStudy(geneName):
	global args
	global rootedDir
	global consNameDict
	global genepythia
	global reGeneName
	global alnRepo
	os.chdir(rootedDir.reports)
	workdir=rootedDir.reports+'/'+geneName
	mkdirp(workdir)
	cmdList=['cd '+workdir]
	annotPath=consNameDict[geneName]+'/annotation'
	seqPath=consNameDict[geneName]+'/'+args.filter
	cmdList.append('ln -sf '+annotPath+'/uniprot.tab uniprot.tab')
	cmdList.append('ln -sf '+annotPath+'/name.tab name.tab')
	cmdList.append('ln -sf '+seqPath+' algn')
	cmdList.append('ln -sf '+annotPath+'/kegg.tab kegg.tab')
	cmdList.append('ln -sf '+annotPath+'/go.tab go.tab')
	cmdList.append('ln -sf '+annotPath+'/alias.txt alias.txt')
	prefixTerm={
		'nipah':'\'nipah,paramyxovirus,paramyxoviridae,hendra,hennipavirus\'',
		'immunoviro':'\'innate immunity,innate immune,virus,viral,immune response\'',
		'metabo':'\'ROS,reactive oxygen species,oxydative stress,free radicals,reactive nitrogen species\'',
		'neuro':'\'brain damage,encephalitis,neuropathology,neurological disorders,neurological deseases\''
	}
	cmdListPBS=['cd '+workdir]
	for prefix,term in prefixTerm.iteritems():
		options={
			'-gene':reGeneName.match(geneName).group(3),
			'-alias':'alias.txt',
			'-prefix':prefix,
			'-term':term
		}
		cmdListPBS.append(genepythia.create(workdir,options))
	submitShell(cmdList)
	#jobID=submitQsubWithPBS(createPBS(cmdListPBS,geneName+'_biblio',rootedDir.pbsLogs+'/'+geneName+'_biblio.e',rootedDir.pbsLogs+'/'+geneName+'_biblio.o',workdir=workdir))
	#viewAlgn('algn.fa','algn',geneName)  # voir GRAPH

	# TODO posDict!!! key = block and value = ref if . give last in  no . for block
	old_ref=1
	posDict=dict()
	posAlnDict=dict()
	with open(workdir+'/algn/posDict.tab') as posDictFile:
		posDictFile.readline()
		for line in posDictFile.readlines():
			ref,aln,exon,block=line.rstrip().split("\t")
			if block != '' and block != '.':
				posAlnDict[tcod(block)]=tcod(aln)
				if ref=='.':
					posDict[tcod(block)]=tcod(old_ref)
				else:
					posDict[tcod(block)]=tcod(ref)
					old_ref=ref
	if geneDict[geneName]=='bs':
		mkdirp(workdir+'/bs')
		os.chdir(workdir+'/bs')
		readBEB(geneName)
		bebfile=open('BEB.tab','r')
		algn=dict()
		fasta=open('../algn/codon_aln_blocks.fa','r')
		for line2 in fasta.readlines():
			line2=line2.rstrip()
			if line2[:1]=='>':
				key=line2.lstrip('>')
				algn[key]=''
			else:
				algn[key]+=line2
		fasta.close()
		for line in bebfile.readlines():
			pos=line.rstrip().split("\t")[0]
			refpos=posDict[pos]
			alnpos=posAlnDict[pos]
			#print(geneName+':'+pos)
			if pos=='':
				continue
			posFile=open(pos+'.uniprot.tab','w')
			with open('../uniprot.tab','r') as uniprot:
				head=None
				for feature in uniprot.readlines():
					featureList=feature.rstrip().split("\t")
					if head==None:
						posFile.write(feature)
						head=dict()
						index=0
						for var in featureList:
							head[var]=index
							index+=1
					elif eval(refpos)>eval(featureList[head['start']]) and eval(refpos)<=eval(featureList[head['end']]):
						posFile.write(feature)
			posFile.close()
			alnFile=open(pos+'.aln.tab','w')
			alnFile.write("species\tcodons\tamino acids\n")
			for key in algn:
				codon=algn[key][eval(pos)*3-3:eval(pos)*3]
				try: aa=str(Seq(codon,generic_dna).translate())
				except: aa='N'
				alnFile.write(key+"\t"+codon+"\t"+aa+"\n")
			alnFile.close()
		bebfile.close()
		os.chdir('..')
	Report(args.gene_rmd,geneName,jobID=[jobID])
	os.chdir('..')
cmdGeneral=['cd '+rootedDir.reports]
cmdGeneral.append('cp '+rootedDir.results+'/parameters.tab .')
if args.adj=='yes':
	cmdGeneral.append('cp '+rootedDir.results+'/testsResults_padj.tab geneMethods.tab')
else:
	cmdGeneral.append('cp '+rootedDir.results+'/testsResults_pval.tab geneMethods.tab')
cmdGeneral.append('cp '+rootedDir.results+'/testsResults_raw.tab tests.tab')
cmdGeneral.append('ln -sf '+alnRepo+'/reports/go.tab '+rootedDir.reports+'/go.tab')
cmdGeneral.append('ln -sf '+alnRepo+'/reports/kegg.tab '+rootedDir.reports+'/kegg.tab')


if args.adj=='yes':
	cmdGeneral.append('cp '+rootedDir.results+'/venn_padj.jpg venn.jpg')
else:
	cmdGeneral.append('cp '+rootedDir.results+'/venn_pval.jpg venn.jpg')
submitShell(cmdGeneral)

#TODO ADD GENEGROUPFILTER

geneDict=dict() # pass, bs, no
head=None
with open(rootedDir.reports+'/geneMethods.tab','r') as statFile:
	for line in statFile.readlines():
		lineList=line.rstrip().split("\t")
		if head==None:
			head=dict()
			index=0
			for var in lineList:
				head[var]=index
				index+=1
		else:
			if lineList[head['BranchSites']]=='TRUE':
				geneDict[lineList[head['gene_name']]]='bs'
				#print(lineList[head['gene_name']])
			elif lineList[head['Branch']]=='TRUE':
				geneDict[lineList[head['gene_name']]]='pass'
			else:
				geneDict[lineList[head['gene_name']]]='no'
Report(args.general_rmd,'',args.general_biblio)

for key in geneDict:
	if geneDict[key]!='no':
		byGeneStudy(key)
