#!/usr/bin/env python
import argparse
#add gitRepository
version='SEDMATCHGITVERSION'
year=2016
author='Julien Fouret'
contact='julien.fouret@fouret.me'
parser = argparse.ArgumentParser(description="""

#-----------------------|gwEvol-paml|-----------------------#
     Genome-wide screening of coding sequences with PAML
-------------------------------------------------------------
This software serializes genome-wide analyses of molecular ev-
olution on HPC infrastructure. All coding sequences are expec-
ted to be produced using gwAlign-Unify. 

The ete3 software is needed to drive PAML analysis. 

All models available in ete3 can be runned. However default
arguments will only run models necessary for Branch and 
Branch-site positive selection analyses.

""",epilog="Version : "+str(version)+"\n"+str(year)+"\nAuthor : "+author+" for more informations or enquiries please contact "+contact,formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('-aln_dir', metavar='/path', required=True, help="""
MSAs repository produced with gwAlign-Unify""")
parser.add_argument('-mark', metavar='ete3_mark', required=True, help="""

branch(es) to mark as target (through ete3) for positive selection analysis (using names in the tree)""")
parser.add_argument('-tree', metavar='tree.nh', required=True, help="""
Tree file with newick format""")
parser.add_argument('-filter', metavar='name', required=False,default='default_filter', help="""
Matching the -name argument provided to gwAlign-Unify -mode stat_filter
(default='default_filter')""")
parser.add_argument('-outDir', metavar='/path', required=True, help="""Output directory""")
parser.add_argument('-queue', metavar='name',default=None, required=False, help="""Queue/partition for HPC
(default=None)""")
parser.add_argument('-models', metavar='model1,model2,...', required=False,default='M0,b_free,M1,bsA1,bsA', help="""
List of model (ete3 names) to be computed
(default='M0,b_free,M1,bsA1,bsA')
""")
parser.add_argument('-batchLim', metavar='N',default='20', required=False, help="""
number of genes per jobs
(default='20')
""")
parser.add_argument('-v',action='store_true', help="verbose")
args=parser.parse_args()

import re
import os
import subprocess
import sys
from upype import *

rootedDir=RootDir(args.outDir,True,{'paml':str})

# Define variable and process arguments
Nlim=int(args.batchLim)
treeFile=os.path.abspath(args.tree)
alnRepo=os.path.abspath(args.aln_dir)
mark=args.mark
modelList=args.models.split(',')
prefix=args.filter

rootedDir.addCommand('ete3',"ete3","ete3 version | sed 's/ Tools.*$//g'")

def tree_reduce(oriTree,oriAln,oriMark):
	"""
	@summary: adjust the tree and the mark to be specified in ete3 if there is missing sequences in the alignment.
	"""

	from Bio import phylo
	from Bio import AlignIO
	tree = Phylo.read(oriTree, 'newick')
	leafs==[x.name for x in tree.get_terminals()]
	aligned_species=[x.name for x in AlignIO.read(oriAln, 'phylip')]
	import re 
	comma3=False
	comma2=False
	comma1=False
	m=re.match("(.*),,(.*)",oriMark)
	if m:
		comma2=True
		markList=[m.group(1),m.group(2)]
	else:
		m=re.match("(.*),,,(.*)",oriMark)
		if m:
			comma3=True
			markList=[m.group(1),m.group(2)]
		else:
			comma1=True
			markList=oriMark.split(",")

	for leaf in leafs:
		if not leaf in aligned_species:
			if leaf in markList:
				if comma1:
					
			tree.prune(leaf)


filterPathDict=dict()
with open(alnRepo+'/reports/kgPathDictFile.tab','r') as kgPathDictFile:
	#Change for name in keys!
	for line in kgPathDictFile.readlines():
		key,value=line.rstrip().split("\t")
		filterPathDict[key]=value+'/'+prefix

rootedDir.addSerializer("gwEvol_paml",Nlim,queue=args.queue,ncpus='1',mem="2gb",workdir=rootedDir.paml)
cmdList=list()
for symbol in filterPathDict.keys():
	genePath=rootedDir.paml+'/'+symbol
	alnPath=filterPathDict[symbol]+"/tcs_filtered_aln.fa"
	### check min Size
	if not os.path.exists(alnPath):
		err_logger("::gwEvol::No alignment available for "+symbol+" at "+alnPath)
		continue
	mkdirp(genePath)
	opt={
		'--noimg':'',
		'-t':treeFile,
		'--alg':alnPath,
		'-o':prefix,
		'--mark':mark,
		'--cpu':'1'
	}
	pos=['1> '+prefix+'.out','2> '+prefix+'.err']
	for model in modelList:
		opt['--models']=model
		cmdList.append(rootedDir.getCommand('ete3',genePath,opt,pos,subprogram='evol'))
	rootedDir.serialize("gwEvol_paml",cmdList)
	cmdList=list()
rootedDir.finishSerializer("gwEvol_paml")

# save rootedDir and save logs then exit
saveRoot(rootedDir)
sys.exit()
